// Package replay implements event-sourced recovery for pipeline runs.
// It reads the Action Log (pkg/actionlog) and reconstructs state by
// replaying the pipeline definition forward: re-executing pure steps,
// injecting recorded state deltas for effectful steps, and following
// recorded routing decisions. See EXECUTION_ENGINE_REDESIGN_V2.md §4.2.
package replay

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/asaidimu/hermes/pkg/actionlog"
	"github.com/asaidimu/hermes/pkg/core"
	"github.com/asaidimu/hermes/pkg/effect"
	"github.com/asaidimu/hermes/pkg/pipeline"
	"github.com/asaidimu/hermes/pkg/store"
)

// StepAddress is an alias for pipeline.EntryAddress, pointing to a
// specific stage (and optionally step) within a pipeline.
type StepAddress = pipeline.EntryAddress

// DefinitionResolver returns the PipelineDefinition for a pipeline id.
// Called by the Replayer to obtain the definition to replay: the root
// pipeline id during Rebuild, and subpipeline definition ids when walking
// fork/bounded/distribute stages. Implementations should resolve any
// pipeline in the compiled workflow — the runtime resolves from
// Workflow.Pipelines plus the subpipeline definitions embedded in stages
// (Workflow.FindPipeline); dynamic distribute children are regenerated by
// the parent stage's DynamicPipelines closure and never need resolving.
//
// Resolves by PIPELINE id (not run id) — see #review-20260910-003.
type DefinitionResolver func(pipelineID string) (*pipeline.PipelineDefinition, bool)

// Replayer reconstructs pipeline state from the Action Log by replaying
// the pipeline definition forward. It is the consumer side of the
// event-sourced recovery design (§4.2).
type Replayer struct {
	log     actionlog.Store
	resolve DefinitionResolver
}

// NewReplayer creates a Replayer that reads from the given action log
// and resolves pipeline definitions via the provided resolver.
func NewReplayer(log actionlog.Store, resolve DefinitionResolver) *Replayer {
	if log == nil {
		log = actionlog.NopLog{}
	}
	return &Replayer{
		log:     log,
		resolve: resolve,
	}
}

// Rebuild reconstructs the run's state by replaying the pipeline
// definition forward, consulting the Action Log at effectful-step
// boundaries and routing decision points. rootPipelineID identifies the
// run's primary pipeline (whose entries drive the top-level walk);
// subpipeline entries are replayed against their own definitions when the
// walk reaches the stage that forked them (#review-20260910-015).
//
// Returns the reconstructed Store and the resume address:
//   - Empty StepAddress (Stage=="") means the run completed — no
//     forward execution needed.
//   - Non-empty StepAddress means forward execution should resume at
//     that step (the first unrecorded effectful step, or the first
//     stage whose routing decision wasn't recorded). A StepAddress with
//     Pipeline set addresses a stage inside the Index-th subpipeline of a
//     pipelines-mode stage (a child that paused mid-run).
func (rp *Replayer) Rebuild(ctx context.Context, runID, rootPipelineID string) (store.Store, StepAddress, error) {
	entries, err := rp.latestEntries(ctx, runID)
	if err != nil {
		return nil, StepAddress{}, fmt.Errorf("actionlog.All: %w", err)
	}

	def, ok := rp.resolve(rootPipelineID)
	if !ok {
		return nil, StepAddress{}, core.NewSystemError(core.ErrCodeNotFound,
			"no pipeline definition for run "+runID)
	}

	// Partition the run's entries per pipeline: root entries (this
	// definition) vs each subpipeline instance's own entries. See the
	// resolved #review-20260910-015 note on the old flat indexes.
	groups := partitionByPipeline(entries, rootPipelineID)

	st := store.NewMemoryStore(nil)
	addr, err := rp.walkDef(ctx, def, groups, st)
	if err != nil {
		return nil, StepAddress{}, err
	}
	return st, addr, nil
}

// StateAt reconstructs the exact state map as it existed immediately
// after stepAddr completed, by replaying the Action Log up to (and
// including) that step. Used for debugging, audit, and "why did this
// run take the branch it took" questions — without the engine having
// ever separately stored a snapshot at that point.
//
// Addresses are resolved against the ROOT pipeline: subpipeline
// contributions that happened before the target stage are folded in
// (child entries replayed and merged, mirroring runtime merge semantics),
// but an address INSIDE a subpipeline instance is not supported.
func (rp *Replayer) StateAt(ctx context.Context, runID, rootPipelineID string, addr StepAddress) (map[string]any, error) {
	// @note #review-20260910-024 issue status=resolved priority=P2 tags=#review,#replay,#determinism : StateAt result depended on Go's randomized map iteration order
	// @author hermes-review
	//
	// StateAt walked def.Stages and, inside the target stage, iterated
	// stage.Steps (a map) with an early return on the target step. Go
	// randomizes map iteration, so whether a sibling step's recorded
	// delta was folded in before the early return flipped run to run:
	// StateAt(…, StepAddress{Stage: "stage-1", Step: "step-b"}) returned
	// state WITH step-a's delta about half the time and WITHOUT it the
	// other half (caught by TestStateAt failing intermittently in the
	// full-suite run). An unrecorded effectful sibling also aborted the
	// whole projection mid-stage, order-dependently.
	//
	// Resolved: steps in a stage run concurrently (Stage.Execute spawns
	// one goroutine per step), so "state at step X" is only stable as
	// "just before X's own delta landed". The projection now folds in
	// every non-target sibling deterministically — recorded deltas for
	// effectful steps, re-execution for pure ones — skipping the
	// target's own contribution, and treats an unrecorded effectful
	// sibling as "no delta yet" instead of aborting.
	entries, err := rp.latestEntries(ctx, runID)
	if err != nil {
		return nil, fmt.Errorf("actionlog.All: %w", err)
	}

	def, ok := rp.resolve(rootPipelineID)
	if !ok {
		return nil, core.NewSystemError(core.ErrCodeNotFound,
			"no pipeline definition for run "+runID)
	}

	groups := partitionByPipeline(entries, rootPipelineID)

	st := store.NewMemoryStore(nil)
	if err := rp.foldDef(ctx, def, groups, st, addr); err != nil {
		return nil, err
	}
	return exportState(st)
}

// @note #review-20260910-015 issue status=resolved priority=P2 tags=#review,#replay,#concurrency : Log indexing by bare stage/step IDs collapsed concurrent subpipeline instances
// @author hermes-review
// @see #review-20260910-003
//
// Resolved: log entries now carry a PipelineID (schema change to
// actionlog.Entry, stamped by RunContextImpl.appendLog, ExecuteStageSteps
// and the runtime's resume entry), and the Replayer partitions entries per
// pipeline (partitionByPipeline) instead of indexing all of a run's entries
// by bare stage/step id. Workflows compiled with distribute (and fork)
// clone the SAME body stage/step ids into N concurrent child pipelines; the
// old flat index kept only the FIRST completion entry per step id, silently
// dropped the other children's deltas, and let one child's routing handle
// steer every child's replay. Now each child instance's entries are replayed
// against its own definition and store (replaySubpipelineStage — child defs
// resolved statically, or regenerated via the stage's DynamicPipelines
// closure exactly like the runtime does), seeded/cloned like
// ExecuteSubPipelines, and merged into the parent with the runtime's
// resultKey/default-merge semantics (mergeChildResult). Child pauses bubble
// as nested EntryAddress.Pipeline resume addresses. Combined with the
// resolver fix in #review-20260910-003, event-sourced recovery is faithful
// for subpipeline-bearing pipelines, not just linear ones.

// --- pipeline-grouped replay ---

// pipelineGroups holds a run's action log entries partitioned by the
// pipeline that produced them. Entries without a PipelineID (written
// before the field existed) are treated as root entries.
type pipelineGroups map[string][]actionlog.Entry

// partitionByPipeline splits entries per PipelineID. Root entries are those
// whose PipelineID equals rootPipelineID or is empty (backward compatibility
// with logs written before #review-20260910-015 stamped the field).
func partitionByPipeline(entries []actionlog.Entry, rootPipelineID string) pipelineGroups {
	groups := pipelineGroups{}
	for _, e := range entries {
		key := e.PipelineID
		if key == "" {
			key = rootPipelineID
		}
		groups[key] = append(groups[key], e)
	}
	return groups
}

// isPipelinesModeStage reports whether a stage runs subpipelines (mirrors
// RunContextImpl.Run's mode detection).
func isPipelinesModeStage(stage pipeline.Stage) bool {
	return len(stage.Pipelines) > 0 || stage.DynamicPipelines != nil
}

// resolveChildPipelines resolves a pipelines-mode stage's child definitions
// exactly like the runtime does: DynamicPipelines (if set) wins over the
// static list, evaluated against the reconstructed state snapshot.
func resolveChildPipelines(stage pipeline.Stage, st store.Store) ([]pipeline.PipelineDefinition, error) {
	resolved := stage.Pipelines
	if stage.DynamicPipelines != nil {
		state, err := exportState(st)
		if err != nil {
			return nil, err
		}
		resolved = stage.DynamicPipelines(state)
	}
	return resolved, nil
}

// newChildStore seeds a child pipeline store like ExecuteSubPipelines does:
// a fresh store from stage.Config["initialState"] when configured, else a
// clone of the parent store at this point of the replay.
func newChildStore(stage pipeline.Stage, parent store.Store) (store.Store, error) {
	if stage.Config != nil {
		if is, ok := stage.Config["initialState"].(map[string]any); ok && is != nil {
			return store.NewFreshStore(store.DeepCopyMap(is)), nil
		}
	}
	cloned, err := parent.Clone()
	if err != nil {
		return nil, fmt.Errorf("clone parent store for subpipeline: %w", err)
	}
	return cloned, nil
}

// stageForked reports whether the parent's own entries contain a
// KindSubpipelineForked marker for the stage — proof the stage actually ran.
func stageForked(own []actionlog.Entry, stageID string) bool {
	for _, e := range own {
		if e.Kind == actionlog.KindSubpipelineForked && e.StageID == stageID {
			return true
		}
	}
	return false
}

// walkDef replays one pipeline definition forward against st, consuming the
// entries produced by THAT pipeline (groups[pipelineID]); subpipeline
// entries are consumed recursively when their fork stage is reached.
// Returns the resume address: empty when the definition completed, or the
// stage/step (optionally nested in a subpipeline via EntryAddress.Pipeline)
// where forward execution should pick up.
func (rp *Replayer) walkDef(ctx context.Context, def *pipeline.PipelineDefinition, groups pipelineGroups, st store.Store) (StepAddress, error) {
	own := groups[def.ID]
	byStep := indexByStepID(own)
	routes := indexByStage(own)
	checkpoints := indexCheckpoints(own)

	// Build a stage-indexed lookup for jump resolution.
	stageIdx := make(map[string]int, len(def.Stages))
	for i, s := range def.Stages {
		stageIdx[s.ID] = i
	}

	currentIdx := 0
	for currentIdx < len(def.Stages) {
		stage := def.Stages[currentIdx]

		// Pipelines-mode stage: replay each child instance against its
		// own entries and definition, then merge like the runtime does.
		if isPipelinesModeStage(stage) {
			if !stageForked(own, stage.ID) {
				// No fork entry — the stage never ran. Forward
				// execution resumes at this stage.
				return StepAddress{Stage: stage.ID}, nil
			}

			childResume, err := rp.replaySubpipelineStage(ctx, stage, groups, st)
			if err != nil {
				return StepAddress{}, err
			}
			if os.Getenv("REPLAY_DEBUG") != "" {
				fmt.Printf("DEBUG parent=%s stage=%s childResume=%+v\n", def.ID, stage.ID, childResume)
			}
			if childResume.Stage != "" {
				// A child paused mid-run: bubble the nested resume
				// address (mirrors the runtime's nested checkpoint).
				return StepAddress{
					Stage: stage.ID,
					Step:  childResume.Step,
					Pipeline: &pipeline.SubPipelineAddress{
						Index: childResume.index,
						Stage: childResume.Stage,
					},
				}, nil
			}
			// Children settled — fall through to routing.
		} else {
			// Steps-mode stage: process all steps.
			for _, step := range stage.Steps {
				if step.Effect == int(effect.SideEffecting) {
					entry, done := byStep[step.ID]
					if done {
						// Effectful step completed: inject its recorded
						// state delta. Don't re-execute — side effects
						// must not be duplicated.
						if err := applyRecordedDelta(st, entry); err != nil {
							return StepAddress{}, fmt.Errorf(
								"apply recorded delta for step %s: %w", step.ID, err)
						}
						continue
					}
					// Not yet recorded — this is where forward
					// execution resumes.
					return StepAddress{Stage: stage.ID, Step: step.ID}, nil
				}
				// Pure: re-execute for real against reconstructed state.
				if err := replayStep(ctx, st, step); err != nil {
					return StepAddress{}, fmt.Errorf(
						"replay pure step %s: %w", step.ID, err)
				}
			}
		}

		// All steps/children in this stage processed. Check routing.
		if handle, routed := routes[stage.ID]; routed && handle != "" {
			// Pause routes: either the "__pause__" wait marker (pause
			// without an explicit resume stage) or an explicit resume
			// stage that matches this stage's own pause checkpoint.
			// Both mean execution WAITED here instead of jumping.
			if ckptResume, isCkpt := checkpoints[stage.ID]; isCkpt &&
				(handle == pipeline.PauseRouteHandle || handle == ckptResume) {
				if !resumedAfterCheckpoint(own, stage.ID) {
					// The latest pause has not been resumed yet — the
					// log ends inside the wait. Forward execution
					// starts at the checkpoint's resume stage (the
					// walk there decides whether anything is left to
					// do, so an empty resume stage still yields a
					// resumable address instead of a silent
					// "completed").
					return StepAddress{Stage: ckptResume}, nil
				}
				// The resumed segment is recorded in the log: continue
				// from the resume stage.
				if targetIdx, found := stageIdx[ckptResume]; found {
					if targetIdx == currentIdx {
						// Degenerate pause on the last stage: the
						// recorded resume address is the pausing
						// stage itself. Forward execution re-enters
						// it (the pause router re-evaluates buffered
						// events); returning the address here keeps
						// the walk from spinning on itself.
						return StepAddress{Stage: stage.ID}, nil
					}
					currentIdx = targetIdx
					continue
				}
			}
			// Routing decision recorded — follow it. Handle maps to
			// a stage ID for jump instructions.
			if targetIdx, found := stageIdx[handle]; found {
				currentIdx = targetIdx
				continue
			}
			// @note #review-20260910-023 issue status=resolved priority=P1 tags=#review,#replay,#resume : Rebuild returns the pausing stage as the resume address, so every resumed run re-pauses forever
			// @author hermes-review
			// @see #review-20260910-001
			//
			// Resolved: a recorded pause route (PauseRouteHandle, "__pause__")
			// is a WAIT MARKER, not a jump target. Previously the lookup below
			// failed (no stage is named "__pause__") and fell through to
			// "unknown target — treat as resume point", returning the PAUSING
			// stage as the resume address. The resumed run then re-entered the
			// pause stage, whose router paused again — an infinite pause loop
			// that made event-sourced resume unusable for any workflow that
			// actually pauses (masked until now: the pause node was a silent
			// no-op, see #review-20260910-007, and hand-built runtime tests
			// hit the vacuous zero-definition path, see
			// #review-20260910-022). A pause checkpoint records where execution
			// should continue (ResumeAt) — resolve the marker through it.
			if handle == pipeline.PauseRouteHandle {
				if resumeAt, ok := checkpoints[stage.ID]; ok {
					if targetIdx, found := stageIdx[resumeAt]; found {
						if targetIdx == currentIdx {
							// Degenerate pause on the last stage: the
							// recorded resume address is the pausing
							// stage itself. Forward execution re-enters
							// it (the pause router re-evaluates buffered
							// events); returning the address here keeps
							// the walk from spinning on itself.
							return StepAddress{Stage: stage.ID}, nil
						}
						currentIdx = targetIdx
						continue
					}
				}
			}
			// Unknown target — treat as resume point.
			return StepAddress{Stage: stage.ID}, nil
		}

		// No routing entry or advance — natural progression to next stage.
		currentIdx++
	}

	// Run completed — all stages replayed without hitting an unrecorded
	// effectful step or missing routing decision.
	return StepAddress{}, nil
}

// childResume is the resume address produced by a child pipeline walk, plus
// the child's index within the parent stage's pipeline list (for the nested
// SubPipelineAddress).
type childResume struct {
	index int
	Stage string
	Step  string
}

// replaySubpipelineStage replays a pipelines-mode stage's children: each
// child's entries are replayed against its own store (seeded/cloned like
// ExecuteSubPipelines does) and merged into the parent store with the same
// resultKey/default-merge semantics as RunContextImpl.Run. The caller must
// check stageForked before invoking.
//
// Returns a resume with Stage != "" when a child paused mid-run (the caller
// bubbles it as a nested EntryAddress.Pipeline address); a zero childResume
// when all children settled.
func (rp *Replayer) replaySubpipelineStage(ctx context.Context, stage pipeline.Stage, groups pipelineGroups, st store.Store) (childResume, error) {
	resolved, err := resolveChildPipelines(stage, st)
	if err != nil {
		return childResume{}, err
	}

	for i := range resolved {
		child := &resolved[i]

		childStore, err := newChildStore(stage, st)
		if err != nil {
			return childResume{}, fmt.Errorf("subpipeline %s: %w", child.ID, err)
		}

		addr, err := rp.walkDef(ctx, child, groups, childStore)
		if err != nil {
			return childResume{}, fmt.Errorf("replay subpipeline %s: %w", child.ID, err)
		}
		if addr.Stage != "" {
			return childResume{index: i, Stage: addr.Stage, Step: addr.Step}, nil
		}

		if err := mergeChildResult(st, child, childStore, stage, i, len(resolved), groups[child.ID]); err != nil {
			return childResume{}, err
		}
	}
	return childResume{}, nil
}

// mergeChildResult applies the runtime's post-join merge semantics for one
// child: resultKey-configured stages store the child's final state (or error
// detail) under resultKey[":" + childID]; default merge folds application
// keys (non "__" prefixed) from successful children into the parent state.
func mergeChildResult(
	parent store.Store,
	child *pipeline.PipelineDefinition,
	childStore store.Store,
	stage pipeline.Stage,
	index, total int,
	childEntries []actionlog.Entry,
) error {
	// Infer the child's terminal status from its own entries: a failed or
	// aborted child run appends KindPipelineFailed; anything else that
	// completed is a success. (The runtime's join EVENT carries per-child
	// statuses, but the durable join log entry records only the stage id —
	// inference from entries is the replay-faithful source.)
	succeeded := true
	for _, e := range childEntries {
		if e.Kind == actionlog.KindPipelineFailed {
			succeeded = false
			break
		}
	}

	if stage.Config != nil {
		if resultKey, ok := stage.Config["resultKey"].(string); ok && resultKey != "" {
			var mergeVal any
			if succeeded {
				final, err := exportState(childStore)
				if err != nil {
					return fmt.Errorf("export subpipeline %s state: %w", child.ID, err)
				}
				mergeVal = final
			} else {
				mergeVal = map[string]any{"pipelineId": child.ID, "status": "failed"}
			}
			key := resultKey
			if total > 1 {
				key = resultKey + ":" + child.ID
			}
			return parent.Update(context.Background(), store.SetValue(key, mergeVal))
		}
	}

	if !succeeded {
		return nil
	}
	final, err := exportState(childStore)
	if err != nil {
		return fmt.Errorf("export subpipeline %s state: %w", child.ID, err)
	}
	return parent.Update(context.Background(), func(state map[string]any) error {
		for k, v := range final {
			if !strings.HasPrefix(k, "__") {
				state[k] = v
			}
		}
		return nil
	})
}

// foldDef folds every stage of a definition into st for StateAt projections:
// recorded deltas for effectful steps, re-execution for pure ones, recursive
// subpipeline folding + merging for pipelines-mode stages. When addr names a
// stage/step of THIS definition, folding stops there per the resolved
// #review-20260910-024 semantics: siblings of the target step are folded,
// the target's own contribution is skipped, and an empty StepAddress.Stage
// match ("state at stage entry") returns before the stage's steps.
func (rp *Replayer) foldDef(ctx context.Context, def *pipeline.PipelineDefinition, groups pipelineGroups, st store.Store, addr StepAddress) error {
	own := groups[def.ID]
	byStep := indexByStepID(own)

	for _, stage := range def.Stages {
		if isPipelinesModeStage(stage) {
			if !stageForked(own, stage.ID) {
				// Stage never ran — contributes nothing.
				if stage.ID == addr.Stage {
					return nil
				}
				continue
			}
			resolved, err := resolveChildPipelines(stage, st)
			if err != nil {
				return err
			}
			for i := range resolved {
				child := &resolved[i]
				childStore, err := newChildStore(stage, st)
				if err != nil {
					return fmt.Errorf("subpipeline %s: %w", child.ID, err)
				}
				if err := rp.foldDef(ctx, child, groups, childStore, StepAddress{}); err != nil {
					return fmt.Errorf("replay subpipeline %s: %w", child.ID, err)
				}
				if err := mergeChildResult(st, child, childStore, stage, i, len(resolved), groups[child.ID]); err != nil {
					return err
				}
			}
			if stage.ID == addr.Stage {
				return nil
			}
			continue
		}

		// Stop at the target stage before processing any steps.
		if stage.ID == addr.Stage && addr.Step == "" {
			return nil
		}

		if stage.ID == addr.Stage {
			// Step-level target: fold in every sibling's contribution
			// regardless of map iteration order, skip the target's own.
			for stepID, step := range stage.Steps {
				if stepID == addr.Step {
					continue
				}
				if err := foldStep(ctx, st, byStep, step); err != nil {
					return err
				}
			}
			return nil
		}

		// Stages before the target: fold in every step.
		for _, step := range stage.Steps {
			if err := foldStep(ctx, st, byStep, step); err != nil {
				return err
			}
		}
	}
	return nil
}

// foldStep folds one step's contribution into a replayed store: the
// recorded delta for an effectful step (a no-op when the step has no
// recording yet), or re-execution for a pure step.
func foldStep(ctx context.Context, st store.Store, byStep map[string]actionlog.Entry, step pipeline.Step) error {
	if step.Effect == int(effect.SideEffecting) {
		entry, done := byStep[step.ID]
		if !done {
			return nil
		}
		return applyRecordedDelta(st, entry)
	}
	return replayStep(ctx, st, step)
}

// --- helpers ---

// latestEntries reads the run's most recent attempt (highest rerunIndex).
// Returns nil when no log exists — the caller then resumes from the start.
func (rp *Replayer) latestEntries(ctx context.Context, runID string) ([]actionlog.Entry, error) {
	idx, err := rp.log.LatestRerunIndex(ctx, runID)
	if err != nil {
		return nil, err
	}
	if idx < 0 {
		return nil, nil
	}
	return rp.log.All(ctx, runID, idx)
}

// indexByStepID builds a map from StepID to the first completed entry.
// For effectful steps, this is the KindEffectCompleted or KindEffectFailed
// entry that records the step's outcome. Callers must pre-filter entries to
// a single pipeline's own entries (#review-20260910-015).
func indexByStepID(entries []actionlog.Entry) map[string]actionlog.Entry {
	m := make(map[string]actionlog.Entry)
	for _, e := range entries {
		if e.StepID != "" && (e.Kind == actionlog.KindEffectCompleted || e.Kind == actionlog.KindEffectFailed) {
			if _, exists := m[e.StepID]; !exists {
				m[e.StepID] = e
			}
		}
	}
	return m
}

// indexByStage builds a map from StageID to the routing handle of the
// most recent KindRouted entry for that stage.
func indexByStage(entries []actionlog.Entry) map[string]string {
	m := make(map[string]string)
	for _, e := range entries {
		if e.Kind == actionlog.KindRouted && e.StageID != "" {
			m[e.StageID] = e.Handle
		}
	}
	return m
}

// checkpointSeq returns the Seq of the LATEST pause checkpoint recorded for
// the stage (0 when the stage never paused).
func checkpointSeq(entries []actionlog.Entry, stageID string) uint64 {
	var last uint64
	for _, e := range entries {
		if e.Kind == actionlog.KindCheckpoint && e.StageID == stageID && e.Seq > last {
			last = e.Seq
		}
	}
	return last
}

// resumedAfterCheckpoint reports whether the log shows a resume of the
// stage's latest pause: a KindResumed entry recorded after that checkpoint.
// A pause whose latest checkpoint has no following KindResumed means the run
// is STILL WAITING at that pause — replay must stop there and hand back the
// checkpoint's resume address instead of walking on as if the route had been
// taken.
func resumedAfterCheckpoint(entries []actionlog.Entry, stageID string) bool {
	ckptSeq := checkpointSeq(entries, stageID)
	if ckptSeq == 0 {
		return false
	}
	for _, e := range entries {
		if e.Kind == actionlog.KindResumed && e.Seq > ckptSeq {
			return true
		}
	}
	return false
}

// indexCheckpoints builds a map from StageID to the resume stage recorded in
// that stage's pause checkpoint (KindCheckpoint / "pipeline:pause"). The
// checkpoint's ResumeAt is where execution continues after the wait — replay
// resolves pause wait-marker routes through it (see walkDef).
func indexCheckpoints(entries []actionlog.Entry) map[string]string {
	m := make(map[string]string)
	for _, e := range entries {
		if e.Kind != actionlog.KindCheckpoint || e.StageID == "" || len(e.Output) == 0 {
			continue
		}
		var ckpt pipeline.PipelineCheckpoint
		if err := json.Unmarshal(e.Output, &ckpt); err != nil {
			continue
		}
		if ckpt.ResumeAt.Stage != "" {
			m[e.StageID] = ckpt.ResumeAt.Stage
		}
	}
	return m
}

// applyRecordedDelta injects the state delta recorded in an action log
// entry into the store. The delta is a flat map of key→value changes
// that were applied when the effectful step originally ran.
func applyRecordedDelta(st store.Store, entry actionlog.Entry) error {
	if len(entry.Output) == 0 {
		return nil // no delta recorded (step had no state effect)
	}
	var delta map[string]any
	if err := json.Unmarshal(entry.Output, &delta); err != nil {
		return fmt.Errorf("unmarshal state delta: %w", err)
	}
	return st.Update(context.Background(), func(state map[string]any) error {
		for k, v := range delta {
			state[k] = v
		}
		return nil
	})
}

// replayStep re-executes a pure step's Action against the store. The
// step's Action closure captures the node logic; we call it with a
// read-only state snapshot and apply the returned mutator.
func replayStep(ctx context.Context, st store.Store, step pipeline.Step) error {
	if step.Action == nil {
		return nil
	}
	// Build a minimal PipelineContext for the step. During replay,
	// the step doesn't need bus/logger/resource resolution — it just
	// needs to compute its mutator.
	pCtx := pipeline.NewReplayContext()
	var mutator store.Mutator
	var actionErr error
	readErr := st.Read(func(state map[string]any) error {
		mutator, actionErr = step.Action(ctx, pCtx, state)
		return nil
	})
	if readErr != nil {
		return readErr
	}
	if actionErr != nil {
		return actionErr
	}
	if mutator != nil {
		return st.Update(ctx, mutator)
	}
	return nil
}

// exportState returns a deep copy of the store's current state.
func exportState(st store.Store) (map[string]any, error) {
	var state map[string]any
	err := st.Read(func(s map[string]any) error {
		state = store.DeepCopyMap(s)
		return nil
	})
	if state == nil {
		state = make(map[string]any)
	}
	return state, err
}
