// AUTO-GENERATED by scripts/build.ts — do not edit.
import type { NodeDef } from "./types";

import * as _arithmetic from "../pkg/nodes/arithmetic/arithmetic";
import * as _code from "../pkg/nodes/code/code";
import * as _database from "../pkg/nodes/database/database";
import * as _delay from "../pkg/nodes/delay/delay";
import * as _for_each from "../pkg/nodes/for-each/foreach";
import * as _gemini from "../pkg/nodes/gemini/gemini";
import * as _http from "../pkg/nodes/http/http";
import * as _if from "../pkg/nodes/if/if";
import * as _query from "../pkg/nodes/query/query";
import * as _switch from "../pkg/nodes/switch/switch";
import * as _transformer from "../pkg/nodes/transformer/transformer";
import * as _trigger from "../pkg/nodes/trigger/trigger";
import * as _try_catch from "../pkg/nodes/try-catch/trycatch";
import * as _while from "../pkg/nodes/while/while";

function pick(mod: Record<string, unknown>): NodeDef {
  const def = Object.values(mod).find(
    (v): v is NodeDef =>
      typeof v === "object" &&
      v !== null &&
      typeof (v as any).kind === "string" &&
      typeof (v as any).handles !== "undefined" &&
      typeof (v as any).configSchema === "object",
  );
  if (!def) throw new Error("Node module exports no NodeDef: " + JSON.stringify(Object.keys(mod)));
  return def;
}

export const NODE_DEFS: Record<string, NodeDef> = {
  "arithmetic": pick(_arithmetic),
  "code": pick(_code),
  "database": pick(_database),
  "delay": pick(_delay),
  "for-each": pick(_for_each),
  "gemini": pick(_gemini),
  "http": pick(_http),
  "if": pick(_if),
  "query": pick(_query),
  "switch": pick(_switch),
  "transformer": pick(_transformer),
  "trigger": pick(_trigger),
  "try-catch": pick(_try_catch),
  "while": pick(_while),
};
